src/Environment/Parameters.yml
src/Message/Broker/Redis.yml
src/Scheduler/Cache.php
src/Scheduler/Cache.yml
src/Scheduler/CacheInterface.php
src/Semaphore/Resource.yml

- Allow users to specify `neighborhoods.kojo.environment.parameters.lock_prefix` to allow multiple Kōjō servers on a single execution environment

Feature/KOJO-28 | Namespace Sever and Redis locks 

---

src/Process/Job.php
src/Process/Pool/Logger/Formatter.php
src/Process/Pool/Logger/FormatterInterface.php

Previously Kōjō would create a log message panicking a job when an un-caught exception bubbled all the way up to the `\Neighborhoods\Kojo\Process\Job` level. This error message didn't provide any actionable info as to what caused the job to panic in the first place.
```json
{
"time": "Wed, 10 Oct 18 16:14:27.887391 UTC",
"level": "critical",
"process_id": "290",
"process_path": "/server[282]/root[286]/job[290]",
"message": "Panicking job with ID[14]."
}
```
This pull request will take the "previous exception" attached to the \RunTimeException and run it through a formatter. This will help to give more context to what caused the job to panic.
```json
{
"time": "Wed, 10 Oct 18 16:14:27.887391 UTC",
"level": "critical",
"process_id": "290",
"process_path": "/server[282]/root[286]/job[290]", …
```

Create a formatter for the \Throwable type and use when jobs Panic

---

src/Api/V1/Worker/Service.php
src/Api/V1/Worker/ServiceInterface.php

Sometimes workers need to be aware of their job ID (e.g. for patterns where a job's input data is stored externally, keyed by job ID)
Since this is purely an orthogonal addition to the userspace API, I'm not sure if a fitness function is necessary (or what it would demonstrate), but let me know if I should create one

KOJO-49 | Expose Job ID in userspace

---

src/Api/V1/Worker/Service.php

Ran across this issue trying to use `requestRetry()` in userspace, the datetime provided by the worker is never stored.
[Fitness Function](https://github.com/neighborhoods/KojoFitness/pull/12)

KOJO-57 | Store DateTime from Worker retryRequest()

---

src/Api/V1/Worker/Service.php
src/Api/V1/Worker/Service.yml
src/Api/V1/Worker/ServiceInterface.php
src/Foreman.php
src/Foreman.yml

**BREAKING CHANGE:** Current users could rely on the `Foreman` automatically starting and naming transactions, which will no longer be the case.
@alexberryman @danielbloom and I will have to modify our existing workers if we want that functionality
[FitnessFunction here](https://github.com/neighborhoods/KojoFitness/pull/13)

KOJO-65 | Expose NewRelic class in userspace

---

docker/build.sh

This PR addresses two tiny shellcheck warnings that appear when examining `docker/build.sh`:
- https://github.com/koalaman/shellcheck/wiki/SC2086
- https://github.com/koalaman/shellcheck/wiki/SC2002
These admittedly won't have any real impact on running the bash script correctly, but it's nice to get rid of the noise in my linter. :)

Clean up shellcheck warnings

---

composer.json

This PR declares the `pcntl` extension as an explicit dependency in the composer.json file for this project. Useful for providing user feedback about whether this application is runnable in a given context.

Declare ext-pcntl as composer.json dependency

---

src/Process/Pool/Logger.php
src/Process/Pool/Logger/Message.php
src/Process/Pool/Logger/MessageInterface.php

```php
$this->getApiV1WorkerService()->getLogger()->notice('MESSAGE', ['w00t!', 'p00t'=>'!']);
```
produces
```json
{
"time": "Fri, 21 Dec 18 22:13:17.905085 UTC",
"level": "notice",
"process_id": "793",
"process_path": "\/server[781]\/root[785]\/job[793]",
"message": "MESSAGE",
"context": {
"0": "w00t!",
"p00t": "!"
},
"context_json_last_error": 0
}
```
whilst
```php
$this->getApiV1WorkerService()->getLogger()->notice('MESSAGE', [NAN]);
```
produces
```json
{
"time": "Fri, 21 Dec 18 21:45:26.754997 UTC",
"level": "notice",
"process_id": "742",
"process_path": "\/server[734]\/root[738]\/job[742]",
"message": "MESSAGE",
"context": [
],
"context_json_last_error": 7
}
```

Log a JsonSerializable object as context

---

src/Db/Schema/VersionAbstract.php

Re-opening https://github.com/neighborhoods/kojo/pull/23 because the `4.x.x` branch was deleted

KOJO-42 | Wrap schema changes so that types that Doctrine is unfamiliar with will be registered as strings

---

src/Foreman.php
src/Maintainer.php
src/Maintainer/Delete.php
src/Message/Broker/Redis.php
src/Process/Job.php
src/Process/Pool/Logger/FormatterInterface.php
src/Scheduler.php

* Catch Throwables instead of Exceptions.
* Use the Throwable message as the logged message.
* Use the Throwable __toString method as the logged context.
* Deprecate `Logger\FormatterInterface::getFormattedThrowableMessage`

Improve Throwable Logging

---

src/Db/Schema/VersionAbstract.php

Two problems: one was that we weren't committing the transaction, the other was that we assembled the schema changes but didn't actual execute them

Actually perform schema changes

---

bin/kojo
pylon/src/DependencyInjection/ContainerBuilder/Facade.php
src/ErrorHandler.php
src/ErrorHandlerInterface.php
src/Foreman.php
src/Process/Forked.php
src/Process/Forked/Exception.php
src/Process/Job.php
src/Process/Listener/Command.php
src/Process/Listener/Mutex/Redis.php
src/Process/Pool.php
src/Process/Pool/Server.php
src/Process/Pool/Strategy.php
src/Process/Pool/Strategy/Server.php
src/Process/Pool/Strategy/Worker.php
src/Process/PoolAbstract.php
src/Process/Root.php
src/Process/Signal.php
src/Process/SignalInterface.php
src/ProcessAbstract.php
src/Runtime/ExceptionInterface.php

* cleanup bin/kojo
* create and use an aggressive error handler for kojo space
* restore to VM error handler for user space
* update kojo container builder to comply with symfony deprecations
* make Mucha happy with newlines and some whitespace updates
* remove wait counting
* remove block and unblock
* update many log levels from info to debug
* remove pcntl_sigwaitinfo
* expose toggling signal buffering on and off
* catch and gracefully handle fork faults
* add a Forked Exception
* disable signal buffer for non-reactive processes
* catch a signal processor throwable

Fixes to signal handling, updates to logging, add error handler, handle fork fault (OOM), disable signal buffering for non-reactive Procs 

---

src/Maintainer.php

A Job completes and is deleted after the Maintainer loads a collection
of potentially crashed Jobs but before reloading the Job in a protected
critical region.

Fix reschedule crashed Jobs race condition

---

src/Scheduler.php
src/Scheduler.yml

The fix is a lot simpler than I thought. I figured I would have to mess around with `Service\Create`, where the [actual exception was being thrown](https://github.com/neighborhoods/kojo/blob/4.x/src/Service/Create.php#L78), but I think kojo should still throw an exception if userspace tries to dynamically schedule a disabled job

KOJO-73 | Gracefully handle disabled statically scheduled job types

---

src/Scheduler.php

This library defaults to whatever `date_default_timezone_get()` is, make it explicit that we want to use UTC

KOJO-85 | Explicitly use UTC for cron

---

src/Api/V1/Job/Type/Registrar.php
src/Type/Service/Create.php
src/Type/Service/Create/AwareTrait.php

Before:
```
$firstJobTypeService = (new Kojo\Api\V1\Job\Type\Service())->addYmlServiceFinder($finder);
$firstJobTypeRegistrar = $firstJobTypeService->getNewJobTypeRegistrar();
// register first job
$secondJobTypeService = (new Kojo\Api\V1\Job\Type\Service())->addYmlServiceFinder($finder);
$secondJobTypeRegistrar = $secondJobTypeService->getNewJobTypeRegistrar();
// register second job
...
```
After:
```
$jobTypeService = (new Kojo\Api\V1\Job\Type\Service())->addYmlServiceFinder($finder);
$firstJobTypeRegistrar = $jobTypeService->getNewJobTypeRegistrar();
// register first job
$secondJobTypeRegistrar = $jobTypeService->getNewJobTypeRegistrar();
// register second job
...
```
Since kojo doesn't cache its DI container in the filesystem, re-creating it for every job type was expensive …

KOJO-86 | Remove some shallow cloning from job type registrar

---

src/ProcessAbstract.php

I added the `ini_set('memory_limit','-1');` because I kept getting OOM errors trying to log OOM errors in a test script, I don't think it'll cause any problems

KOJO-82 | Add error_get_last() to shutdown event

---

composer.json
src/Message/Broker/Redis.php
src/Process/Job.php
src/Process/Listener/Command.php
src/Process/Pool/Logger.php
src/Process/Pool/Strategy.php
src/Process/Pool/Strategy/Server.php
src/Process/Pool/Strategy/Worker.php

Normalize the exception to be both string and object based:
```json
{
"time": "Mon, 01 Apr 19 02:10:05.589843 UTC",
"level": "critical",
"process_id": "912",
"process_path": "/server[867]/root[871]/job[912]",
"message": "Panicking job with ID[13362].",
"context": {
"exception_sting": "TypeError: Argument 1 passed to Neighborhoods\\KojoFitnessUseCase46\\V1\\Worker\\Delegate::onlyTakesIntegers() must be of the type integer, string given, called in /var/www/html/kojo_fitness.neighborhoods.com/UseCase46/src/V1/Worker/Delegate.php on line 33 and defined in /var/www/html/kojo_fitness.neighborhoods.com/UseCase46/src/V1/Worker/Delegate.php:45\nStack trace:\n#0 /var/www/html/kojo_fitness.neighborhoods.com/UseCase46/src/V1/Worker/Delegate.php(33): …
```

Pass exceptions as an object under the 'exception' key, and normalize that key if it's a throwable

---

src/Process/Listener/Mutex/Redis.php
src/Process/Listener/Mutex/Redis.yml

The watchdog created two connections. The first was named with a process's UUID (and thus was used for determining if the process that held a mutex was still alive), and the second wasn't named but still used to execute the blocking push/pop command
Other actors trying to acquire a mutex would base their actions on the state of the first connection, which didn't offer the guarantee that the second connection did (i.e. that the worker would be killed if that connection was closed). This change uses the same connection for naming and the blocking operation (i.e. the intended behavior)
The choice of redis connection to use from the Repository is based on `\Neighborhoods\Kojo\Message\Broker\Redis::_getRedisClient()`

HOTFIX | Modify watchdog to use one named redis connection

---

Dockerfile
src/Process/Pool/Logger/Message.php
src/Process/Pool/Logger/Message/Builder.php
src/Process/Pool/Logger/MessageInterface.php

- This will be the first release targeted to the 5.x release of Kōjō. 
- Remove the following top level logging keys in favor the of the `kojo_metadata` structure as documented in the [4.15.0 release notes](https://github.com/neighborhoods/kojo/releases/tag/4.15.0):
- kojo_process
- kojo_job
- process_id
- process_path

Feature/KOJO-157 | remove deprecated logging structure

---

src/Foreman.php
src/Foreman.yml

The error handler is really just a safety net, as a general rule we should be `catch`ing `Error`s
Because the crash vs panic behavior affects userspace (and "times crashed" is exposed through the Worker Service API), this is going into 5.x
Any users upgrading to the version this PR goes into will have to make sure they're not relying on "crash-loop" behavior. If retrying a job when an exception is thrown is desirable behavior, the exception must be caught in userspace, and the Worker Service API must be used to request a retry

KOJO-96 | Panic job instead of crashing on userspace exceptions

---

src/ForemanInterface.php

One minor addition to https://github.com/neighborhoods/kojo/pull/91/files
I dunno why my earlier testing didn't hit this problem, probably some autoloader or DI caching

KOJO-96 | Removing unnecessary interface method

---

src/Process/Pool/Strategy.php

When I added this stuff, I treated this `SIGCHLD`-handler-triggered method as if it was only responsible to replacing the exited process (which the JSCLP doesn't need), but it's also where the Root's process pool model gets cleaned up and re-synchronized with reality

KOJO-180 | Clean up Root's Process Pool after JSCLP exit

---

src/Process/Root.php

In situations where an execution environment starts up and there are many "pending job" messages in redis, the previous version of the code would attempt to add singletons to an already-full process pool

KOJO-178 | Guard against full process pool when Root is polling singletons

---

composer.json
composer.lock

It's not used and it's been deprecated, so off you go. `phpunit/dbunit` is also deprecated, but there's some [weirdness](https://github.com/sebastianbergmann/dbunit/issues/217) around it, and it's a dev dependency, I'm going to err on the side of leaving it in

KOJO-182 | Remove unused Zend\Db dependency

---

src/Db/Schema/VersionAbstract.php
src/Process/Pool/Server.php
src/Process/Pool/Server.yml

Exactly what it says on the tin
There has always existed a [critical region](https://github.com/neighborhoods/kojo/blob/5.x/src/Db/Schema/VersionAbstract.php#L23-L37) for migrations, since it's possible to run multiple instances of `kojo db:setup:install` concurrently, but it was very unlikely until we decided that we want the server process to automatically run any available migrations on startup. Considering that schema exceptions bubbling up from the critical region into the server process would cause the kojo runtime to crash, I added some guards so migrations run from either entrypoint would handle them gracefully
[Related KojoFitness UseCase](https://github.com/neighborhoods/KojoFitness/pull/26)

KOJO-173 | Auto-migration logic

---

src/Data/Job/FromArrayBuilder.php
src/JobStateChange.php
src/JobStateChangeInterface.php
src/Process/JobStateChangelogProcessor.php
src/Process/JobStateChangelogProcessor.yml
src/Process/Pool/Strategy.php
src/Process/Root.php

* Added casts for `Data\Job\FromArrayBuilder` logic because serialization is a mess
* Added logic in JSCLP for reading JSCs from RDBMS, emitting `info` messages, and deleting them. Batch size defaults to 50 but is easily changed from userspace through the parameter YAML file

KOJO-150 | Emit messages for job state changes

---

src/Process/Root.php

It's not doing anything currently and the process is being weird in some edge cases for agent service

HOTFIX | Stop spawning JSCLP process
